#!/usr/bin/env python3
"""
rename-previews.py

Renames existing preview images from sanitized-name form to hash-based names,
using meta.json to map preset names to their 20-char SHA-256 hashes.

The old preview filenames were generated by the JS _sanitize() function:
  replace(/[^a-zA-Z0-9 _\-+().]/g, '_').trim()

We try two matching strategies:
  1. Exact match: stem == original filename stem (after removing extension)
  2. Sanitize match: sanitize(stem) == preview filename stem

Usage:
  python3 scripts/rename-previews.py [--dry-run] [group-dir ...]

  If no group-dir is given, processes all groups under public/butterchurn-presets/
  and public/shadertoy-presets/.

  --dry-run: print what would be renamed without doing it.
"""

import sys
import os
import json
import re
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sanitize(name):
    """Mirror of the JS _sanitize() function in PreviewBatch.js"""
    name = re.sub(r'[^a-zA-Z0-9 _\-+().]', '_', name)
    return name.strip()


def process_group(group_dir, dry_run=False):
    meta_path = os.path.join(group_dir, 'meta.json')
    previews_dir = os.path.join(group_dir, 'previews')

    if not os.path.isfile(meta_path):
        print(f"  SKIP (no meta.json): {group_dir}")
        return 0, 0, 0

    if not os.path.isdir(previews_dir):
        print(f"  SKIP (no previews/): {group_dir}")
        return 0, 0, 0

    with open(meta_path) as f:
        meta = json.load(f)

    img_ext = meta.get('imageExt', 'jpg')
    src_map = meta.get('srcMap', {})  # hash -> "Original Name.json"

    # Build lookup: sanitized_stem -> hash, and exact_stem -> hash
    by_exact = {}    # "Original Name" -> hash
    by_sanitized = {}  # sanitize("Original Name") -> hash

    for h, filename in src_map.items():
        stem = filename.rsplit('.', 1)[0]  # remove .json or .glsl
        by_exact[stem] = h
        san = sanitize(stem)
        by_sanitized[san] = h

    renamed = 0
    already_ok = 0
    skipped = 0

    for fname in sorted(os.listdir(previews_dir)):
        fpath = os.path.join(previews_dir, fname)

        # Skip non-files and directories
        if not os.path.isfile(fpath):
            continue

        base, ext = os.path.splitext(fname)
        ext = ext.lstrip('.')

        # Already hash-named (20 hex chars)
        if re.fullmatch(r'[0-9a-f]{20}', base):
            already_ok += 1
            continue

        # Try to find the hash for this preview
        h = by_exact.get(base) or by_sanitized.get(base)

        if h is None:
            print(f"  NOMATCH: {fname}")
            skipped += 1
            continue

        new_name = f"{h}.{img_ext}"
        new_path = os.path.join(previews_dir, new_name)

        if fname == new_name:
            already_ok += 1
            continue

        if dry_run:
            print(f"  RENAME: {fname!r} -> {new_name!r}")
        else:
            os.rename(fpath, new_path)

        renamed += 1

    return renamed, already_ok, skipped


def main():
    args = sys.argv[1:]
    dry_run = '--dry-run' in args
    if dry_run:
        args.remove('--dry-run')

    if args:
        group_dirs = args
    else:
        # Auto-discover all group directories with previews/
        group_dirs = []
        for category in ['butterchurn-presets', 'shadertoy-presets']:
            cat_dir = os.path.join(ROOT, 'public', category)
            if not os.path.isdir(cat_dir):
                continue
            for entry in sorted(os.listdir(cat_dir)):
                gdir = os.path.join(cat_dir, entry)
                if os.path.isdir(gdir) and os.path.isdir(os.path.join(gdir, 'previews')):
                    group_dirs.append(gdir)

    total_renamed = total_ok = total_skipped = 0
    for gdir in group_dirs:
        rel = os.path.relpath(gdir, ROOT)
        print(f"{rel}/")
        r, ok, sk = process_group(gdir, dry_run=dry_run)
        print(f"  renamed={r}, already_ok={ok}, no_match={sk}")
        total_renamed += r
        total_ok += ok
        total_skipped += sk

    print()
    print(f"Total: renamed={total_renamed}, already_ok={total_ok}, no_match={total_skipped}")
    if dry_run:
        print("(dry run — nothing was changed)")


if __name__ == '__main__':
    main()
